### PR TITLE
fix: allows `parse_api_date` to handle various date formats and intro…

### LINKED ISSUE #245: Missing description of the `last_update` field
Problem: Notice it's missing a description of the `last_update` field. Also `last_update` # is in the wrong format. It should be a date, but it's numeric. Need to file an issue # either in `epidatr` or in `delphi-epidata`, plus update the documentation page.

Fix: meta$last_update <- as.POSIXct(meta$last_update, origin = "1970-01-01")

### LINKED ISSUE #319: bug: default `pub_covid_hosp_facility()` fails
Using the facility in the documentation example. Other facilities also fail. Note that this is the CRAN version with R 4.5.0 on a Mac.

``` r
library(epidatr)
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.5.0 (2025-04-11)
#>  os       macOS Sequoia 15.5
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       America/Vancouver
#>  date     2025-05-30
#>  pandoc   3.4 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/aarch64/ (via rmarkdown)
#>  quarto   1.6.37 @ /usr/local/bin/quarto
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  askpass       1.2.1   2024-10-04 [1] CRAN (R 4.5.0)
#>  backports     1.5.0   2024-05-23 [1] CRAN (R 4.5.0)
#>  cachem        1.1.0   2024-05-16 [1] CRAN (R 4.5.0)
#>  checkmate     2.3.2   2024-07-29 [1] CRAN (R 4.5.0)
#>  cli           3.6.5   2025-04-23 [1] CRAN (R 4.5.0)
#>  digest        0.6.37  2024-08-19 [1] CRAN (R 4.5.0)
#>  epidatr     * 1.2.1   2025-03-20 [1] CRAN (R 4.5.0)
#>  evaluate      1.0.3   2025-01-10 [1] CRAN (R 4.5.0)
#>  fastmap       1.2.0   2024-05-15 [1] CRAN (R 4.5.0)
#>  fs            1.6.6   2025-04-12 [1] CRAN (R 4.5.0)
#>  glue          1.8.0   2024-09-30 [1] CRAN (R 4.5.0)
#>  htmltools     0.5.8.1 2024-04-04 [1] CRAN (R 4.5.0)
#>  httr          1.4.7   2023-08-15 [1] CRAN (R 4.5.0)
#>  jsonlite      2.0.0   2025-03-27 [1] CRAN (R 4.5.0)
#>  knitr         1.50    2025-03-16 [1] CRAN (R 4.5.0)
#>  lifecycle     1.0.4   2023-11-07 [1] CRAN (R 4.5.0)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.5.0)
#>  MMWRweek      0.1.3   2020-04-22 [1] CRAN (R 4.5.0)
#>  openssl       2.3.2   2025-02-03 [1] CRAN (R 4.5.0)
#>  pillar        1.10.2  2025-04-05 [1] CRAN (R 4.5.0)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.5.0)
#>  purrr         1.0.4   2025-02-05 [1] CRAN (R 4.5.0)
#>  R6            2.6.1   2025-02-15 [1] CRAN (R 4.5.0)
#>  reprex        2.1.1   2024-07-06 [1] CRAN (R 4.5.0)
#>  rlang         1.1.6   2025-04-11 [1] CRAN (R 4.5.0)
#>  rmarkdown     2.29    2024-11-04 [1] CRAN (R 4.5.0)
#>  rstudioapi    0.17.1  2024-10-22 [1] CRAN (R 4.5.0)
#>  sessioninfo   1.2.3   2025-02-05 [1] CRAN (R 4.5.0)
#>  tibble        3.2.1   2023-03-20 [1] CRAN (R 4.5.0)
#>  vctrs         0.6.5   2023-12-01 [1] CRAN (R 4.5.0)
#>  withr         3.0.2   2024-10-28 [1] CRAN (R 4.5.0)
#>  xfun          0.52    2025-04-02 [1] CRAN (R 4.5.0)
#>  xml2          1.3.8   2025-03-14 [1] CRAN (R 4.5.0)
#>  yaml          2.3.10  2024-07-26 [1] CRAN (R 4.5.0)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/library
#>  * ── Packages attached to the search path.
#> 
#> ──────────────────────────────────────────────────────────────────────────────
h <- pub_covid_hosp_facility("050063", epirange(20240101, 20240301)) # works
h <- pub_covid_hosp_facility("050063") # fails
#> Error in charToDate(x): character string is not in a standard unambiguous format
#> Timing stopped at: 0.136 0.005 0.601
```

<sup>Created on 2025-05-30 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by JavierMtzRdz**
### Checklist

Please:

- [x] Make sure this PR is against "dev", not "main" (unless this is a release
      PR).
- [x] Request a review from one of the current epidatr main reviewers:
      brookslogan, dshemetov, nmdefries, dsweber2.
- [x] Makes sure to bump the version number in `DESCRIPTION`. Always increment
      the patch version number (the third number), unless you are making a
      release PR from dev to main, in which case increment the minor version
      number (the second number).
- [x] Describe changes made in NEWS.md, making sure breaking changes
      (backwards-incompatible changes to the documented interface) are noted.
      Collect the changes under the next release number (e.g. if you are on
      1.7.2, then write your changes under the 1.8 heading).

### Change explanations for reviewer

Sometimes, dates and timestamps are not parsed correctly because `parse_api_*` functions do not support the format in the response. For example, `pub_covid_hosp_facility("050063", fetch_args = fetch_args_list(disable_date_parsing = T))` returns dates in various formats in the same column, as shown below.
Screenshot 2026-01-08 at 4 16 32 PM
This can lead to NA results or errors, as seen in #319. Similarly, the format for the `last_update` column in `pub_covidcast_meta()`  is a timestamp, as can be [confirmed here](https://github.com/cmu-delphi/delphi-epidata/blob/2ead81fe006faaa4c4c58c309841f4a82d996aa8/src/acquisition/covidcast/database.py#L475C8-L475C57), which is unsupported.   Therefore, this PR adds `parse_api_datetime` to handle timestamp parsing and enables `parse_api_date` to manage different date formats within the same column. 

### Magic GitHub syntax to mark associated Issue(s) as resolved when this is merged into the default branch

- Resolves #245, #319

### CODE REVIEW

File: R/model.R [hunk 1]
```diff
@@ -251,7 +254,22 @@ date_to_epiweek <- function(value) {
...
+  res <- as.Date(rep(NA, length(value_char)))
+
+  for (fmt in formats) {
+    is_missing <- is.na(res) & !is.na(value_char)
+    if (!any(is_missing)) break
+    attempt <- suppressWarnings(as.Date(value_char[is_missing], format = fmt))
+    res[is_missing] <- attempt
+  }
+  res
+}
```
Comment (dshemetov) [inline R/model.R:292]: What's the advantage of writing this out versus this?
```
  as.Date(as.character(value), tryFormats = c("%Y%m%d", "%Y-%m-%d", "%m%d%Y"))
```

**Review by dshemetov — COMMENTED** [review]
Could you add some tests of the new functions to test-model.R?

File: R/model.R (hunk 1 above)
Comment (JavierMtzRdz) [reply R/model.R:292]: `as.Date(as.character(value), tryFormats = c("%Y%m%d", "%Y-%m-%d", "%m%d%Y"))` assumes that all elements in `value` share the same format, which can lead to `NA` or errors, such as with `pub_covid_hosp_facility("050063")` when parsing variables like `collection_weeks`. In contrast, the new version does not assume that all elements in `value` share the same format.

Comment (dshemetov) [reply R/model.R:292]: Gotcha, thanks. Could you add that as a comment on this function? This is definitely a weirdness of R's API that we're likely to forget after 3 months.

**Comment by JavierMtzRdz** [comment]
The tests and comments have been included!

File: R/model.R [hunk 2]
```diff
@@ -251,7 +254,25 @@ date_to_epiweek <- function(value) {
...
+
+#' @keywords internal
+parse_api_datetime <- function(value) {
+  as.POSIXct(as.numeric(value), origin = "1970-01-01")
```
Comment (dshemetov) [inline R/model.R:296]: So right now this only handles timestamps, but in 3 months, someone might use parse_api_datetime on "YYYYMMDDTHHMMSS" and forget that it's not built for that. Can we either
- rename to something like parse_timestamp_to_datetime
- or make it robust to both timestamp and that datetime format

Comment (JavierMtzRdz) [reply R/model.R:296]: I wrote a version that handles both timestamp and datetime formats. For the datetime format, I relied on an approach similar to `parse_api_date`. Given the different possible combinations, I'm wondering if it might be useful to include [`lubridate::parse_date_time`](https://lubridate.tidyverse.org/reference/parse_date_time.html) instead.

Comment (JavierMtzRdz) [reply R/model.R:296]: I guess the formats should stay fairly consistent.

Comment (dshemetov) [reply R/model.R:296]: Lubridate might be a good direction to go. I think we were hesitant about it due to GPL licensing and we didn't want to constrain our collaborators (does that sound right to you @brookslogan ?). But it looks like [lubridate has been relicensed as MIT](https://github.com/tidyverse/lubridate/issues/968#issuecomment-3657838707) (about 3 weeks ago), which removes that blocker.

Comment (JavierMtzRdz) [reply R/model.R:296]: Hi, @dshemetov! @brookslogan noted that lubridate can also influence the behaviour of other functions. Therefore, I believe we can keep the current implementation and incorporate checks for additional formats in case the API expands.

**Review by dshemetov — CHANGES_REQUESTED** [review]
Sorry, I think `parse_api_datetime` is going to be more work to maintain than is worth. I appreciate you attempting to add the generalization, but it doesn't address timezones and handling that properly will create even more maintenance surface (i.e. opportunities for bugs).

Let's roll back to making this function specific `parse_api_timestamp_to_datetime` and just go with that. We can leave it as a research question whether lubridate could just offload all this work from us in the future.

File: R/endpoints.R [hunk 3]
```diff
@@ -955,7 +955,7 @@ pub_covidcast_meta <- function(fetch_args = fetch_args_list()) {
       create_epidata_field_info("max_value", "float"),
       create_epidata_field_info("mean_value", "float"),
       create_epidata_field_info("stdev_value", "float"),
-      create_epidata_field_info("last_update", "int"),
+      create_epidata_field_info("last_update", "datetime"),
```
Comment (dshemetov) [inline R/endpoints.R]: This should clear up confusion. There's some ambiguity as to whether these field_infos are the type that we get from the API or the type that we should parse into from the API. Because this metadata is mainly used by the `parse_value` function, I think the appropriate interpretation is that it is the type received from the API, so `timestamp` is the correct annotation here.
```suggestion
      create_epidata_field_info("last_update", "timestamp"),
```

File: R/model.R [hunk 4]
```diff
@@ -139,6 +139,7 @@ create_epidata_field_info <- function(name,
     "int",
     "float",
     "date",
+    "datetime",
```
Comment (dshemetov) [inline R/model.R]:
```suggestion
    "timestamp",
```

File: R/model.R [hunk 5]
```diff
@@ -170,6 +171,8 @@ parse_value <- function(info, value, disable_date_parsing = FALSE, reference_wee
     return(value)
   } else if (info$type == "date" && !disable_date_parsing && !inherits(value, "Date")) {
     return(parse_api_date(value))
+  } else if (info$type == "datetime" && !disable_date_parsing && !inherits(value, "POSIXt")) {
+    return(parse_api_datetime(value))
```
Comment (dshemetov) [inline R/model.R]:
```suggestion
  } else if (info$type == "timestamp" && !disable_date_parsing && !inherits(value, "POSIXt")) {
    return(parse_api_timestamp_to_datetime(value))
```

File: R/model.R
Comment (dshemetov) [inline R/model.R:141]:
```suggestion
#' Add metadata to an epidata_field
#' 
#' This function annotates the type of the returned API field. This is used
#' by `parse_value` downstream to determine how to convert the returned data.
create_epidata_field_info <- function(name,
```

Comment (dshemetov) [inline R/model.R:187]:
```suggestion
#' Parse data returned by the API
#' 
#' This function uses the metadata annotations to determine how to parse the incoming data.
#' The data annotation refers to the received API type, rather than the target R type.
#' @importFrom stats na.omit
```

**Review by dshemetov — CHANGES_REQUESTED** [review]
There's ambiguity as to whether `create_epidata_field_info` annotates the received API type or the type we parse into. Following through the code, the only place that uses this metadata field is `parse_data_frame`, which in turn uses `parse_value`. It seems that this function could be interpreted in both ways. Let's just assert that it annotates the returned API type for now. We can address this differently if we choose later.

**Review by dshemetov — APPROVED** [review]
Minor lint bork, otherwise lgtm

**Comment by JavierMtzRdz** [comment]
I updated the documentation parameters to prevent issues with the checks.

**Comment by dshemetov** [comment]
Looks good
